VCS run trigger

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,101 +1,101 @@
-name: 'Terraform'
+# name: 'Terraform'
 
-on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+# on:
+#   push:
+#     branches:
+#       - main
+#   pull_request:
+#     branches:
+#       - main
 
-jobs:
-  terraform:
-    name: 'Terraform Build And Deploy'
-    runs-on: ubuntu-latest
-    timeout-minutes: 5
+# jobs:
+#   terraform:
+#     name: 'Terraform Build And Deploy'
+#     runs-on: ubuntu-latest
+#     timeout-minutes: 5
 
-    steps:
+#     steps:
 
-      - name: Checkout
-        uses: actions/checkout@v2
+#       - name: Checkout
+#         uses: actions/checkout@v2
 
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
+#       - name: Set up QEMU
+#         uses: docker/setup-qemu-action@v1
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v1
 
-      - name: Login to DockerHub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKER_USER }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+#       - name: Login to DockerHub
+#         uses: docker/login-action@v1
+#         with:
+#           username: ${{ secrets.DOCKER_USER }}
+#           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v1
+#         with:
+#           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
-      - name: Build And (or not) Push Frontend docker image
-        id: docker-build
-        env:
-          PUSH_TO_REGISTRY: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          file: .docker/frontend.Dockerfile
-          push: ${{ env.PUSH_TO_REGISTRY }}
-          tags: ${{ secrets.DOCKER_REGISTRY }}:latest
+#       - name: Build And (or not) Push Frontend docker image
+#         id: docker-build
+#         env:
+#           PUSH_TO_REGISTRY: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
+#         uses: docker/build-push-action@v2
+#         with:
+#           context: .
+#           file: .docker/frontend.Dockerfile
+#           push: ${{ env.PUSH_TO_REGISTRY }}
+#           tags: ${{ secrets.DOCKER_REGISTRY }}:latest
 
-      - name: Terraform Format
-        id: fmt
-        working-directory: azure_deploy_example
-        run: terraform fmt
+#       - name: Terraform Format
+#         id: fmt
+#         working-directory: azure_deploy_example
+#         run: terraform fmt
 
-      - name: Terraform Init
-        id: init
-        working-directory: azure_deploy_example
-        run: terraform init
+#       - name: Terraform Init
+#         id: init
+#         working-directory: azure_deploy_example
+#         run: terraform init
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        working-directory: azure_deploy_example
-        run: terraform plan -no-color
-        continue-on-error: true
+#       - name: Terraform Plan
+#         id: plan
+#         if: github.event_name == 'pull_request'
+#         working-directory: azure_deploy_example
+#         run: terraform plan -no-color
+#         continue-on-error: true
 
-      - name: Update Pull Request
-        uses: actions/github-script@0.9.0
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: ${{ steps.plan.outputs.stdout }}
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            <details><summary>Show Plan</summary>
+#       - name: Update Pull Request
+#         uses: actions/github-script@0.9.0
+#         if: github.event_name == 'pull_request'
+#         env:
+#           PLAN: ${{ steps.plan.outputs.stdout }}
+#         with:
+#           github-token: ${{ secrets.GITHUB_TOKEN }}
+#           script: |
+#             const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#             #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#             #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#             <details><summary>Show Plan</summary>
 
-            \`\`\`
-            ${process.env.PLAN}
-            \`\`\`            
-            </details>
+#             \`\`\`
+#             ${process.env.PLAN}
+#             \`\`\`            
+#             </details>
 
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#             *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+#             github.issues.createComment({
+#               issue_number: context.issue.number,
+#               owner: context.repo.owner,
+#               repo: context.repo.repo,
+#               body: output
+#             })
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+#       - name: Terraform Plan Status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        working-directory: azure_deploy_example
-        run: terraform apply -auto-approve
+#       - name: Terraform Apply
+#         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+#         working-directory: azure_deploy_example
+#         run: terraform apply -auto-approve
